name: Nix

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix build .#scip-go

  test-gotip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install ASDF
        uses: asdf-vm/actions/setup@v3

      - name: Install matching Go toolchain
        run: |
          asdf plugin add golang
          asdf install golang

      - name: Install gotip
        run: |
          go install golang.org/dl/gotip@latest
          asdf reshim
          gotip download

      - name: Go version
        run: gotip version

      - name: Install dependencies
        run: gotip get ./...

      - name: Build
        run: gotip build -v ./...

      - name: Test
        run: gotip test -v ./...
